add tooltip
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #10
Opened 2021-11-13 08:09 UTC by alextimoshenko22

2021-11-13 08:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-14 12:35 UTC, GSemikozov requested changes

2021-11-14 12:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
низзя в блоке описывать глобальные стили)

2021-11-14 12:35 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  transform: translate(-50%, -80px);
вместо ненадежных -80px (а если триггером будет картинка высотой 200px?) - лучше явно указать bottom: 100%, а вместо -80px - -8px (фиксированный отступ не зависимо от того какой размер будет у триггера)

2021-11-15 15:24 UTC, alextimoshenko22 commented on 05-lection3/01-tooltip/tooltip.css
> +  transform: translate(-50%, -80px);
при чем я так и думал сначала сделать, спасибо, поправил

2021-11-15 15:44 UTC, alextimoshenko22 commented on 05-lection3/01-tooltip/tooltip.css
> +body {
согласен, я просто задумался как задать отступы (сверху, слева/справа) для этого тултипа, можно ли это сделать через марджины .tooltip?

2021-11-17 14:08 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
можно оставить такой же стиль, просто унести его в тег style хтмл задачи с решением (это вед нужно чисто формально для демонстрации решения)

2021-11-17 14:09 UTC, GSemikozov requested changes

2021-11-17 14:09 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  margin: 60px 50px 0 50px;
марджины на уровне блока нельзя добавлять, нарушает принципы БЭМ и усложняет возможность переиспользовать такой блок

2021-11-17 14:17 UTC, alextimoshenko22 commented on 05-lection3/01-tooltip/tooltip.css
> +  margin: 60px 50px 0 50px;
хорошо понял

2021-11-17 14:17 UTC, alextimoshenko22 commented on 05-lection3/01-tooltip/tooltip.css
> +body {
отлично, спасибо

2021-11-17 18:54 UTC, GSemikozov approved these changes

2021-11-17 18:55 UTC, merged