add modal
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #11
Opened 2021-11-13 15:32 UTC by alextimoshenko22

2021-11-13 15:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-14 12:36 UTC, GSemikozov requested changes

2021-11-14 12:36 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +body {
лишнее

2021-11-15 15:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-15 15:52 UTC, alextimoshenko22 commented on 05-lection3/02-modal/modal.css
> +body {
убрал

2021-11-15 15:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-17 14:10 UTC, GSemikozov approved these changes

2021-11-17 14:10 UTC, merged