Dz mainpage
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #20
Opened 2021-12-01 18:02 UTC by alextimoshenko22

Добавил на главное странице все компоненты, добавил компоненты в страницы, добавил туда также табы

2021-12-01 18:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-03 15:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-05 08:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 15:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 15:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 20:54 UTC, GSemikozov requested changes

2021-12-08 20:54 UTC, GSemikozov commented on components/avatar/avatar.css
> +    width: 160px;
102

2021-12-08 20:54 UTC, GSemikozov commented on components/button/button.css
> +  cursor: not-allowed;
лучше pointer-events: none

2021-12-08 20:54 UTC, GSemikozov commented on components/button/button.css
> +  border: 1px solid #212429;
цвет унести бы в пепременные)

2021-12-08 20:54 UTC, GSemikozov commented on components/calendar/calendar-preview.css
> +.calendar {
тут фактически полностью дублируем стандартный компонент... лучше добавить модификатор для уже имеющегося компонента

2021-12-08 20:54 UTC, GSemikozov commented on components/card/card.css
>      height: 367px;
у карточки можно убрать фиксированную высоту

2021-12-08 20:54 UTC, GSemikozov commented on components/card/card.css
> +.inner-card__body {
класс не по БЭМ

2021-12-08 20:54 UTC, GSemikozov commented on components/histogram/histogram.css
> +  margin-top: 50px;
модификатор относится к блоку, лучше все-таки. не задавать. здесь марджины. Но - настаивать не буду

2021-12-08 20:54 UTC, GSemikozov commented on components/modal/modal.css
> +.modal-margin-top {
класс вне БЭМ

2021-12-08 20:54 UTC, GSemikozov commented on pages/page.css
>  .page {
все-таки .inner-page?

2021-12-13 15:04 UTC, alextimoshenko22 commented on components/card/card.css
> +.inner-card__body {
исправил класс

2021-12-13 15:04 UTC, alextimoshenko22 commented on components/card/card.css
>      height: 367px;
заменил на min-height

2021-12-13 15:05 UTC, alextimoshenko22 commented on components/calendar/calendar-preview.css
> +.calendar {
удалил его и сделал модификатор

2021-12-13 15:05 UTC, alextimoshenko22 commented on components/button/button.css
> +  border: 1px solid #212429;
добавил цвет в переменные

2021-12-13 15:05 UTC, alextimoshenko22 commented on components/button/button.css
> +  cursor: not-allowed;
хорошо

2021-12-13 15:05 UTC, alextimoshenko22 commented on components/avatar/avatar.css
> +    width: 160px;
поправил

2021-12-13 15:09 UTC, alextimoshenko22 commented on components/modal/modal.css
> +.modal-margin-top {
поправил через миксин

2021-12-13 15:20 UTC, alextimoshenko22 commented on pages/page.css
>  .page {
поправил на .inner-page

2021-12-13 15:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-14 19:45 UTC, GSemikozov approved these changes

2021-12-14 19:45 UTC, merged