add button
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #3
Opened 2021-10-28 17:53 UTC by alextimoshenko22

2021-11-01 15:50 UTC, GSemikozov requested changes

2021-11-01 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 8px 16px;
сверху-снизу скорее по 14

2021-11-01 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-family: inherit;
у родителей могут быть разные шрифты, а вот кнопка должна всегда выглядеть консистентно, поэтому - тут лучше явно указать font-family)

2021-11-01 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  text-decoration: underline;
в макете не указано что на ховер у нас будет underline. подчеркивание) и что бордер будет цвета mediumslateblue

2021-11-03 20:33 UTC, GSemikozov requested changes

2021-11-03 20:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: white;
не стоит хардкодить цвет через ключевые слова - лучше убрать это свойство (по цвету можем отнаследоваться, и если надо то переопределить в модификаторе)

2021-11-06 07:16 UTC, alextimoshenko22 commented on 03-lection1/01-button/button.css
> +  color: white;
Согласен, случайно пропустил(

2021-11-10 20:16 UTC, GSemikozov approved these changes

2021-11-10 20:16 UTC, merged