add accordion
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #4
Opened 2021-10-28 18:11 UTC by alextimoshenko22

2021-11-01 15:54 UTC, GSemikozov requested changes

2021-11-03 20:34 UTC, GSemikozov requested changes

2021-11-03 20:34 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    left: 650px;
не будет работать при ресайзе страницы (изменении размера блока)

2021-11-10 20:21 UTC, GSemikozov requested changes

2021-11-10 20:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
не стоит так жестко фиксировать ширину компонента (на мобилке точно будет проблема)

2021-11-10 20:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 650px;
и тут)

2021-11-11 19:28 UTC, alextimoshenko22 commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
готово

2021-11-11 19:29 UTC, alextimoshenko22 commented on 03-lection1/02-accordion/accordion.css
> +    width: 650px;
тоже поправил

2021-11-11 19:29 UTC, alextimoshenko22 commented on 03-lection1/02-accordion/accordion.css
> +    left: 650px;
изменил

2021-11-11 19:29 UTC, alextimoshenko22 commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion-group__item">
Спасибо, понял, поправил

2021-11-14 12:30 UTC, GSemikozov approved these changes

2021-11-14 12:30 UTC, merged