Dz histogram
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #7
Opened 2021-11-02 17:56 UTC by alextimoshenko22

2021-11-02 17:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-03 09:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 09:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 10:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 11:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 20:41 UTC, GSemikozov requested changes

2021-11-03 20:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.wrapper {
советую сначала выполнить правки по скелетону, затем переключится сюда (классы именованы не по БЭМ, надо переделать)

2021-11-06 07:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-08 08:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-08 14:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-08 15:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-08 15:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-11 19:30 UTC, alextimoshenko22 commented on 04-lection2/01-histogram/histogram.css
> +.wrapper {
выполнил

2021-11-14 12:33 UTC, GSemikozov approved these changes

2021-11-14 12:33 UTC, merged