add component page
js-tasks-ru/htmlcss-20211021_ultimatevs pull request #8
Opened 2021-11-09 12:03 UTC by alextimoshenko22

2021-11-09 12:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-10 20:27 UTC, GSemikozov requested changes

2021-11-10 20:27 UTC, GSemikozov commented on pages/page.css
> +.sidebar {
sidebar + component здесь выступают как отдельные блоки, поэтому - их и надо оформить как отдельные блоки в папке components

2021-11-11 12:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-11 13:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-11 13:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-11 13:44 UTC, alextimoshenko22 commented on pages/page.css
> +.sidebar {
поправил

2021-11-11 14:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-14 12:33 UTC, GSemikozov approved these changes

2021-11-14 12:33 UTC, merged